language: python
python:
    - "3.6"
install: 
    - conda install -c conda-forge codecov
script: 
    - coverage run -m unittest discover
after_success: 
    - bash <(curl -s https://codecov.io/bash)
