language: python
os:
    - windows
    - linux
python:
    - "3.6"
    - "3.7"
install:
    - pip install coverage
script:
    - coverage run -m unittest discover
after_success:
    - bash <(curl -s https://codecov.io/bash)
